# Generated by Django 4.0.5 on 2022-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PATIENTDATA', '0006_alter_patientnewdata_lastupdatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnewdata',
            name='MRN',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='patientnewdata',
            name='NoteId',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
